#!/usr/bin/env bash

echo "all: $1" >> Makefile
echo "" >> Makefile
echo "$1: $1.o" >> Makefile
echo "	gcc -o \$@ \$+" >> Makefile
echo "$1.o: $1.s" >> Makefile
echo "	as -o \$@ \$<" >> Makefile
echo "clean: " >> Makefile
echo "	rm -vf $1 *.o" >> Makefile
