#!/usr/bin/env bash

# this script will autogenerate a Makefile for easy compilation of assembler programs

if [ -f Makefile ]; then
  echo "Cleaning directory"
  make clean
  echo "Removed prexisting Makefile"
  rm Makefile
fi

echo "all: $1" >> Makefile
echo "" >> Makefile
echo "$1: $1.o" >> Makefile
echo "	gcc -o \$@ \$+" >> Makefile
echo "$1.o: $1.s" >> Makefile
echo "	as -o \$@ \$<" >> Makefile
echo "clean: " >> Makefile
echo "	rm -vf $1 *.o" >> Makefile
make all
